### ISSUE TITLE
LeTBS doesn't work with parallax mapping techniques

### ISSUE THREAD

**Issue by mjhorvath** [LecodeMV/leTBS#10]
When a battle starts, all map events disappear from the map unless you add "TBS Event" to the events' note fields. But events marked with "TBS Event" are always rendered in a layer below that of the battlers. So you cannot walk "behind" a tall tree during a battle for instance. Actors/battlers always walk "above" map events.

I think you should respect whatever layer the map author puts map events into, whether it is below, the same as, or above battlers.

**Comment by mjhorvath** [comment]
You didn't provide an answer. Does LeTBS now work properly with parallax mapping techniques?

**Comment by LecodeMV** [comment]
Sorry, the issue was posted one year ago, I thought it was unnecessary to update it.

As far as I remember, events marked with "TBS Event" still respect their priority level (below, above or at character level). I however never tested it with parallax mapping. However, rest assured that everything will work fine in this regard on 0.8. The reason I tagged the issues here as obsolete is because the current version is unmaintained, and I'm putting my energy on the next one, 0.8 which pretty much is a re-work from the group-up.
